name: 'Mailgun templates updater action'
description: 'Create a new version for a Mailgun email template using the content of HTML files, and set it as the active version.'
branding:
  icon: 'mail'  
  color: 'red'
inputs:
  mailgun-api-key:
    description: 'Mailgun Primary Account API key'
    required: true
  mailgun-api-host:
    description: 'Mailgun Host. Default: api.mailgun.net'
    required: false
    default: api.mailgun.net
  mailgun-domain-name:
    description: 'Domain Name the template is registered under'
    required: true
  mailgun-template-versions-limit:
    description: 'Number of template versions saved limit (the last ones will be deleted)'
    required: false
    default: '6'
  templates-directory:
    description: 'Path of templates directory'
    required: true
  layout:
    description: 'Path to file to layout'
    required: false
    default: ''
  # synchronize:
  #   description: 'Remove templates in Mailgun if not exists in code'
  #   required: false
  #   default: 'N'
runs:
  using: 'node16'
  main: 'src/main.js'